- hosts: italian-banana-cupcake
  remote_user: banana
  handlers:
    - name: restart cups
      service:
        name: cups
        state: restarted
  tasks:
    - name: Install required packages for cups
      package:
        name:
          - cups
          - avahi-daemon
        state: present
      become: yes

    - service:
        name: cups
        state: started
      become: yes

    - name: Enable web panel
      lineinfile:
        path: /etc/cups/cupsd.conf
        regexp: '^Browsing'
        line: 'Browsing On'
      notify: restart cups
      become: yes

    - name: Enable listening on port
      lineinfile:
        path: /etc/cups/cupsd.conf
        regexp: '^Listen localhost:631'
        line: 'Port 631'
      notify: restart cups
      become: yes

    - name: Enable network sharing
      service:
        name: avahi-daemon
        state: started
      become: yes

    - name: Install packages for I2C for OLED
      package:
        name:
          - python3-dev
          - python-smbus
          - i2c-tools
          - python3-pil
          - python3-pip
          - python3-setuptools
          - python3-rpi.gpio
      become: yes
    - name: Install OLED python lib
      pip:
        name: adafruit-circuitpython-ssd1306
        executable: pip3
    - name: Install git
      package:
        name: git
      become: yes
    
    # gpio support
    - name: Clone WiringBP
      git:
        repo: 'https://github.com/LeMaker/WiringBP.git'
        dest: wiringbp
        version: bananapi
        force: yes
    - name: Make build executable
      file:
        path: wiringbp/build
        mode: '+x'

    - name: Build and install
      command:
        cmd: build
        chdir: wiringbp
        creates: /usr/local/bin/gpio
      become: yes

